### PR TITLE
added dot metric index support

### PR DESCRIPTION
**Pull request by iatsuk**
Support dot metric index (part of issue #15).

Implements support for dot metric index. Keeps the original API. Added tests. I will be grateful for code review.

### CODE REVIEW

**Comment by erikbern** [comment]
@a1k0n mind taking a look?

**Comment by a1k0n** [comment]
Nice, is this using the maximum inner-product search trick like in this paper: https://papers.nips.cc/paper/5329-asymmetric-lsh-alsh-for-sublinear-time-maximum-inner-product-search-mips.pdf ? I didn't know base-annoy had added support for that.

**Comment by a1k0n** [comment]
oh, I see the citation in the original code now. The Microsoft one, right: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/XboxInnerProduct.pdf

**Review by a1k0n — APPROVED** [review]
Looks right to me, w.r.t. the way annoy stores dot_factor.

**Review by a1k0n — APPROVED** [review]
Also every change here is an improvement in code style over the original.

**Comment by erikbern** [comment]
thanks @yatsukav

**Pull request merged**
