### PR TITLE
Added getNearestPqEntries function

### PR DESCRIPTION
**Pull request by LeagueCode**
If a users wants access to node offset and margin, he can use the getNearestPqEntries function

### CODE REVIEW

**Comment by erikbern** [comment]
I'm OK merging this, @a1k0n ?

**Review by a1k0n — APPROVED** [review]
LGTM; what's the use-case -- you just need a bag of NNs, and unsorted is fine?

edit: oh, I see, it gives you the margin directly. Gotcha.

**Comment by a1k0n** [comment]
Do you still have write access here @erikbern?

**Comment by erikbern** [comment]
yeah i can merge!

**Comment by erikbern** [comment]
thanks @LeagueCode !

**Pull request merged**
